export const ROLES = {
  GENERAL_MEMBER: 'GENERAL_MEMBER',
  CHAPTER_OFFICER: 'CHAPTER_OFFICER',
  CHAPTER_LEADER: 'CHAPTER_LEADER',
  WARD_LEADER: 'WARD_LEADER',
  MUNICIPAL_LEADER: 'MUNICIPAL_LEADER',
  DISTRICT_LEADER: 'DISTRICT_LEADER',
  PROVINCIAL_LEADER: 'PROVINCIAL_LEADER',
  NATIONAL_LEADER: 'NATIONAL_LEADER',
  COMMUNITY_REPORTER: 'COMMUNITY_REPORTER',
  PUBLIC_OFFICIAL: 'PUBLIC_OFFICIAL',
  MODERATOR: 'MODERATOR',
  ADMIN: 'ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN',
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];

export const SYSTEM_ROLES = Object.values(ROLES);
