export const CHAPTER_STATUSES = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  DORMANT: 'DORMANT',
  SUSPENDED: 'SUSPENDED',
  REJECTED: 'REJECTED',
  ARCHIVED: 'ARCHIVED',
} as const;

export type ChapterStatus = (typeof CHAPTER_STATUSES)[keyof typeof CHAPTER_STATUSES];

export const ISSUE_STATUSES = {
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  VERIFIED: 'VERIFIED',
  PRIORITIZED: 'PRIORITIZED',
  ESCALATED: 'ESCALATED',
  AWAITING_RESPONSE: 'AWAITING_RESPONSE',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
  REJECTED: 'REJECTED',
  DUPLICATE: 'DUPLICATE',
} as const;

export type IssueStatus = (typeof ISSUE_STATUSES)[keyof typeof ISSUE_STATUSES];

export const PROJECT_STATUSES = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  ONGOING: 'ONGOING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

export type ProjectStatus = (typeof PROJECT_STATUSES)[keyof typeof PROJECT_STATUSES];

export const PROJECT_CATEGORIES = {
  BLOOD_DONATION: 'BLOOD_DONATION',
  CLEANUP: 'CLEANUP',
  TREE_PLANTATION: 'TREE_PLANTATION',
  EDUCATION: 'EDUCATION',
  TOURISM: 'TOURISM',
  CULTURAL: 'CULTURAL',
  DISASTER_RESPONSE: 'DISASTER_RESPONSE',
  COMMUNITY_SERVICE: 'COMMUNITY_SERVICE',
  YOUTH_DEVELOPMENT: 'YOUTH_DEVELOPMENT',
  OTHER: 'OTHER',
} as const;

export type ProjectCategory = (typeof PROJECT_CATEGORIES)[keyof typeof PROJECT_CATEGORIES];

export const MEMBERSHIP_STATUSES = {
  ACTIVE: 'ACTIVE',
  PENDING: 'PENDING',
  EXPIRED: 'EXPIRED',
  CANCELLED: 'CANCELLED',
} as const;

export type MembershipStatus = (typeof MEMBERSHIP_STATUSES)[keyof typeof MEMBERSHIP_STATUSES];
